"""Test production output. Screenshots are generated by execution, never fabricated.
AXE_SOURCE points to a locally installed axe-core engine to enable its WCAG scan.
"""
import json
import os
from pathlib import Path
import shutil
import subprocess
import time
import unittest
import urllib.request
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
ORIGIN = 'http://127.0.0.1:4173'
REPORT = ROOT / 'qa-output'
ROUTES = ['/', '/work/', '/research/', '/life/', '/about/', '/archive/', '/work/kept/', '/work/care-access/', '/work/diatrend/', '/work/nexus-lite/', '/work/bennington/', '/work/differential-learning/', '/work/drug-interaction-checker/']


class PortfolioTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        REPORT.mkdir(exist_ok=True)
        cls.server = subprocess.Popen(['node', 'scripts/serve.mjs'], cwd=ROOT, stdout=subprocess.DEVNULL)
        ready = False
        for _ in range(50):
            try:
                urllib.request.urlopen(ORIGIN, timeout=1).close()
                ready = True
                break
            except OSError:
                time.sleep(.1)
        if not ready:
            cls.server.terminate()
            raise RuntimeError('Production preview server did not start.')
        cls.playwright = sync_playwright().start()
        executable = os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium')
        cls.browser = cls.playwright.chromium.launch(headless=True, **({'executable_path': executable} if executable else {}))

    @classmethod
    def tearDownClass(cls):
        cls.browser.close()
        cls.playwright.stop()
        cls.server.terminate()
        cls.server.wait(timeout=5)

    def setUp(self):
        self.context = self.browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
        self.page = self.context.new_page()
        self.errors = []
        self.page.on('pageerror', lambda error: self.errors.append(str(error)))

    def tearDown(self):
        self.context.close()

    def test_01_all_routes_reflow_at_six_sizes(self):
        results = []
        for width in [320, 360, 390, 768, 1024, 1440]:
            self.page.set_viewport_size({'width': width, 'height': 900})
            for route in ROUTES:
                response = self.page.goto(ORIGIN + route, wait_until='load')
                self.assertEqual(response.status, 200)
                overflow = self.page.evaluate('document.documentElement.scrollWidth > innerWidth + 1')
                results.append({'route': route, 'width': width, 'overflow': overflow})
                (REPORT / 'responsive.json').write_text(json.dumps(results, indent=2))
                self.assertFalse(overflow, f'{route} overflows at {width}')
                self.assertEqual(self.page.locator('h1').count(), 1)
            self.page.goto(ORIGIN, wait_until='load')
            self.page.screenshot(path=str(REPORT / f'home-{width}.png'), full_page=True)
        self.assertEqual(self.errors, [])

    def test_02_mobile_menu_keyboard_and_focus(self):
        self.page.set_viewport_size({'width': 390, 'height': 844})
        self.page.goto(ORIGIN)
        self.page.keyboard.press('Tab')
        self.assertEqual(self.page.evaluate('document.activeElement.textContent'), 'Skip to content')
        self.page.keyboard.press('Enter')
        self.assertEqual(self.page.evaluate('document.activeElement.id'), 'main')
        self.page.locator('.mobile-menu summary').click()
        self.assertTrue(self.page.locator('.mobile-menu').evaluate('(el)=>el.open'))
        self.page.keyboard.press('Escape')
        self.assertFalse(self.page.locator('.mobile-menu').evaluate('(el)=>el.open'))
        self.assertTrue(self.page.locator('.mobile-menu summary').evaluate('(el)=>el===document.activeElement'))

    def test_03_lightbox_restores_focus(self):
        self.page.goto(ORIGIN + '/life/')
        link = self.page.locator('[data-lightbox]').first
        link.click()
        self.assertTrue(self.page.locator('dialog').evaluate('(el)=>el.open'))
        self.page.keyboard.press('Escape')
        self.assertFalse(self.page.locator('dialog').evaluate('(el)=>el.open'))
        self.assertTrue(link.evaluate('(el)=>el===document.activeElement'))

    def test_04_audio_is_opt_in_and_failure_is_visible(self):
        self.page.route('**/media/music/**', lambda route: route.abort())
        self.page.goto(ORIGIN + '/life/')
        self.assertTrue(self.page.locator('audio').evaluate('(el)=>el.paused'))
        self.assertEqual(self.page.locator('audio').count(), 1)
        self.page.locator('[data-track]').nth(1).click()
        self.page.locator('.retry-audio').wait_for(state='visible')
        self.assertIn('could not', self.page.locator('.player-status').inner_text())
        self.assertEqual(self.page.locator('[data-now-playing]').inner_text(), 'ATL')

    def test_05_copy_success_and_denial(self):
        self.context.grant_permissions(['clipboard-read', 'clipboard-write'])
        self.page.goto(ORIGIN)
        self.page.locator('.copy-email').click()
        self.page.wait_for_function("document.querySelector('.copy-status').textContent==='Email copied.'")
        self.page.evaluate("Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('Denied'))},configurable:true})")
        self.page.locator('.copy-email').click()
        self.page.wait_for_function("document.querySelector('.copy-status').textContent.includes('Copy unavailable')")

    def test_06_legacy_hashes_and_404(self):
        self.page.goto(ORIGIN + '/#documents')
        self.page.wait_for_url('**/archive/#documents')
        self.assertEqual(self.page.goto(ORIGIN + '/not-a-real-route/').status, 404)
        self.assertIn('Not here.', self.page.locator('h1').inner_text())

    def test_07_without_javascript(self):
        context = self.browser.new_context(java_script_enabled=False, viewport={'width': 390, 'height': 844})
        page = context.new_page()
        for route in ROUTES:
            page.goto(ORIGIN + route)
            self.assertTrue(page.locator('h1').is_visible())
            self.assertGreater(len(page.locator('main').inner_text()), 100)
        page.goto(ORIGIN + '/life/')
        self.assertEqual(page.locator('audio[controls]').count(), 1)
        self.assertEqual(page.locator('.track-download').count(), 7)
        page.locator('.mobile-menu summary').click()
        self.assertTrue(page.locator('.mobile-menu nav').is_visible())
        context.close()

    def test_08_reduced_motion_and_browser_errors(self):
        self.page.goto(ORIGIN)
        self.assertEqual(self.page.evaluate('getComputedStyle(document.documentElement).scrollBehavior'), 'auto')
        self.assertEqual(self.errors, [])

    def test_09_native_audio_range_requests(self):
        request = urllib.request.Request(ORIGIN + '/media/music/AP.mp3', headers={'Range': 'bytes=0-63'})
        with urllib.request.urlopen(request) as response:
            self.assertEqual(response.status, 206)
            self.assertEqual(len(response.read()), 64)
            self.assertTrue(response.headers['Content-Range'].startswith('bytes 0-63/'))

    @unittest.skipUnless(os.environ.get('AXE_SOURCE'), 'AXE_SOURCE not supplied; full axe scan not run')
    def test_10_axe_wcag_rules(self):
        # Isolated QA context permits test-library injection, not production CSP changes.
        context = self.browser.new_context(bypass_csp=True)
        page = context.new_page()
        report = []
        for route in ROUTES:
            page.goto(ORIGIN + route)
            page.add_script_tag(path=os.environ['AXE_SOURCE'])
            result = page.evaluate("async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})")
            report.append({'route': route, 'violations': result['violations'], 'incomplete': result['incomplete']})
            (REPORT / 'axe.json').write_text(json.dumps(report, indent=2))
            self.assertEqual(result['violations'], [], route)
        context.close()


if __name__ == '__main__':
    unittest.main(verbosity=2)
