"""Test production output. Screenshots are generated by execution, never fabricated.
AXE_SOURCE points to a locally installed axe-core engine to enable its WCAG scan.
"""
import json
import os
from pathlib import Path
import shutil
import subprocess
import time
import unittest
import urllib.request
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parents[1]
ORIGIN = os.environ.get('PORTFOLIO_TEST_ORIGIN', 'http://127.0.0.1:4173')
REPORT = ROOT / 'qa-output'
ROUTES = ['/', '/work/', '/research/', '/life/', '/about/', '/archive/', '/work/kept/', '/work/care-access/', '/work/diatrend/', '/work/nexus-lite/', '/work/bennington/', '/work/differential-learning/', '/work/drug-interaction-checker/']


class PortfolioTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        REPORT.mkdir(exist_ok=True)
        cls.server = None if os.environ.get('PORTFOLIO_TEST_ORIGIN') else subprocess.Popen(['node', 'scripts/serve.mjs'], cwd=ROOT, stdout=subprocess.DEVNULL)
        ready = False
        for _ in range(50):
            try:
                urllib.request.urlopen(ORIGIN, timeout=1).close()
                ready = True
                break
            except OSError:
                time.sleep(.1)
        if not ready:
            if cls.server:
                cls.server.terminate()
            raise RuntimeError('Production preview server did not start.')
        cls.playwright = sync_playwright().start()
        executable = os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium')
        cls.browser = cls.playwright.chromium.launch(headless=True, **({'executable_path': executable} if executable else {}))

    @classmethod
    def tearDownClass(cls):
        cls.browser.close()
        cls.playwright.stop()
        if cls.server:
            cls.server.terminate()
            cls.server.wait(timeout=5)

    def setUp(self):
        self.context = self.browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
        self.page = self.context.new_page()
        self.errors = []
        self.page.on('pageerror', lambda error: self.errors.append(str(error)))

    def tearDown(self):
        self.context.close()

    def load_visible_images(self):
        """Scroll normally to trigger lazy loading; never alter production lazy attributes.
        Waiting for decode prevents below-fold images appearing blank in full-page captures.
        """
        loaded = []
        for image in self.page.locator('main img[src]').all():
            if not image.is_visible():
                continue
            image.scroll_into_view_if_needed()
            result = image.evaluate("""async image => {
                let timeout;
                try {
                    await Promise.race([
                        image.decode(),
                        new Promise((_, reject) => {
                            timeout = setTimeout(() => reject(new Error('Image decode timed out: ' + image.currentSrc)), 15000);
                        })
                    ]);
                    return {src: image.currentSrc, width: image.naturalWidth, height: image.naturalHeight};
                } finally {
                    clearTimeout(timeout);
                }
            }""")
            self.assertGreater(result['width'], 0, result['src'])
            self.assertGreater(result['height'], 0, result['src'])
            loaded.append(result)
        self.page.evaluate("window.scrollTo({top: 0, left: 0, behavior: 'instant'})")
        return loaded

    def test_01_all_routes_reflow_at_six_sizes(self):
        results = []
        for width in [320, 360, 390, 768, 1024, 1440]:
            self.page.set_viewport_size({'width': width, 'height': 900})
            for route in ROUTES:
                response = self.page.goto(ORIGIN + route, wait_until='load')
                self.assertEqual(response.status, 200)
                overflow = self.page.evaluate('document.documentElement.scrollWidth > innerWidth + 1')
                results.append({'route': route, 'width': width, 'overflow': overflow})
                (REPORT / 'responsive.json').write_text(json.dumps(results, indent=2))
                self.assertFalse(overflow, f'{route} overflows at {width}')
                self.assertEqual(self.page.locator('h1').count(), 1)
                if width in [390, 1440] and route != '/':
                    self.page.screenshot(path=str(REPORT / f"{route.strip('/').replace('/', '-')}-{width}.png"))
            self.page.goto(ORIGIN, wait_until='load')
            self.load_visible_images()
            self.page.screenshot(path=str(REPORT / f'home-{width}.png'), full_page=True)
        self.assertEqual(self.errors, [])

    def test_02_mobile_menu_keyboard_and_focus(self):
        self.page.set_viewport_size({'width': 390, 'height': 844})
        self.page.goto(ORIGIN)
        self.page.keyboard.press('Tab')
        self.assertEqual(self.page.evaluate('document.activeElement.textContent'), 'Skip to content')
        self.page.keyboard.press('Enter')
        self.assertEqual(self.page.evaluate('document.activeElement.id'), 'main')
        self.page.locator('.mobile-menu summary').click()
        self.assertTrue(self.page.locator('.mobile-menu').evaluate('(el)=>el.open'))
        self.page.keyboard.press('Escape')
        self.assertFalse(self.page.locator('.mobile-menu').evaluate('(el)=>el.open'))
        self.assertTrue(self.page.locator('.mobile-menu summary').evaluate('(el)=>el===document.activeElement'))

    def test_03_lightbox_restores_focus(self):
        self.page.goto(ORIGIN + '/life/')
        link = self.page.locator('[data-lightbox]').first
        link.click()
        self.assertTrue(self.page.locator('dialog').evaluate('(el)=>el.open'))
        self.page.keyboard.press('Escape')
        self.assertFalse(self.page.locator('dialog').evaluate('(el)=>el.open'))
        self.assertTrue(link.evaluate('(el)=>el===document.activeElement'))

    def test_04_audio_is_opt_in_and_failure_is_visible(self):
        self.page.route('**/media/music/**', lambda route: route.abort())
        self.page.goto(ORIGIN + '/life/')
        self.assertTrue(self.page.locator('audio').evaluate('(el)=>el.paused'))
        self.assertEqual(self.page.locator('audio').count(), 1)
        self.page.locator('[data-track]').nth(1).click()
        self.page.locator('.retry-audio').wait_for(state='visible')
        self.assertIn('could not', self.page.locator('.player-status').inner_text())
        self.assertEqual(self.page.locator('[data-now-playing]').inner_text(), 'ATL')

    def test_05_copy_success_and_denial(self):
        self.context.grant_permissions(['clipboard-read', 'clipboard-write'])
        self.page.goto(ORIGIN)
        self.page.locator('.copy-email').click()
        expect(self.page.locator(".copy-status")).to_have_text("Email copied.")
        self.page.evaluate("Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('Denied'))},configurable:true})")
        self.page.locator('.copy-email').click()
        expect(self.page.locator(".copy-status")).to_contain_text("Copy unavailable")

    def test_06_legacy_hashes_and_404(self):
        self.page.goto(ORIGIN + '/#documents')
        self.page.wait_for_url('**/archive/#documents')
        self.assertEqual(self.page.goto(ORIGIN + '/not-a-real-route/').status, 404)
        self.assertIn('Not here.', self.page.locator('h1').inner_text())

    def test_07_without_javascript(self):
        context = self.browser.new_context(java_script_enabled=False, viewport={'width': 390, 'height': 844})
        page = context.new_page()
        for route in ROUTES:
            page.goto(ORIGIN + route)
            self.assertTrue(page.locator('h1').is_visible())
            self.assertGreater(len(page.locator('main').inner_text()), 100)
        page.goto(ORIGIN + '/life/')
        self.assertEqual(page.locator('audio[controls]').count(), 1)
        self.assertEqual(page.locator('.track-download').count(), 7)
        page.locator('.mobile-menu summary').click()
        self.assertTrue(page.locator('.mobile-menu nav').is_visible())
        context.close()

    def test_08_reduced_motion_and_browser_errors(self):
        self.page.goto(ORIGIN)
        self.assertEqual(self.page.evaluate('getComputedStyle(document.documentElement).scrollBehavior'), 'auto')
        self.assertEqual(self.errors, [])

    def test_09_native_audio_range_requests(self):
        request = urllib.request.Request(ORIGIN + '/media/music/AP.mp3', headers={'Range': 'bytes=0-63'})
        with urllib.request.urlopen(request) as response:
            self.assertEqual(response.status, 206)
            self.assertEqual(len(response.read()), 64)
            self.assertTrue(response.headers['Content-Range'].startswith('bytes 0-63/'))

    @unittest.skipUnless(os.environ.get('AXE_SOURCE'), 'AXE_SOURCE not supplied; full axe scan not run')
    def test_10_axe_wcag_rules(self):
        # Isolated QA context permits test-library injection, not production CSP changes.
        context = self.browser.new_context(bypass_csp=True)
        page = context.new_page()
        report = []
        for route in ROUTES:
            page.goto(ORIGIN + route)
            page.add_script_tag(path=os.environ['AXE_SOURCE'])
            result = page.evaluate("async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})")
            report.append({'route': route, 'violations': result['violations'], 'incomplete': result['incomplete']})
            (REPORT / 'axe.json').write_text(json.dumps(report, indent=2))
            self.assertEqual(result['violations'], [], route)
        context.close()

    def test_11_all_gallery_images_decode(self):
        self.page.goto(ORIGIN + '/life/', wait_until='load')
        loaded = self.load_visible_images()
        expected = len(json.loads((ROOT / '.generated' / 'media.json').read_text())['photos'])
        self.assertEqual(len(loaded), expected)
        (REPORT / 'gallery-media.json').write_text(json.dumps(loaded, indent=2))
        self.assertEqual(self.errors, [])


    def test_12_navigation_and_section_links(self):
        expected = ['/work/', '/research/', '/life/', '/about/', '/archive/']
        for width, selector in [(1440, '.desktop-nav'), (390, '.mobile-menu nav')]:
            self.page.set_viewport_size({'width': width, 'height': 844})
            self.page.goto(ORIGIN + '/work/diatrend/')
            if width == 390:
                self.page.locator('.mobile-menu summary').click()
            self.assertEqual(self.page.locator(selector + ' a').evaluate_all('(links)=>links.map(link=>link.getAttribute("href"))'), expected)
            self.assertEqual(self.page.locator(selector + ' [aria-current="page"]').inner_text(), 'Work')
            self.page.locator(selector + ' a').last.click()
            self.page.wait_for_url('**/archive/')
            self.assertEqual(self.page.locator('h1').inner_text(), 'Archive')
        self.page.goto(ORIGIN + '/work/')
        self.page.get_by_role('navigation', name='Work sections').get_by_role('link', name='Experience', exact=True).click()
        self.assertTrue(self.page.url.endswith('#experience'))
        details = self.page.locator('.experience-entry').first.locator('details')
        details.locator('summary').click()
        self.assertTrue(details.locator('li').first.is_visible())
        self.assertIn('Microsoft Graph', details.inner_text())

    def test_13_home_photos_keep_the_reader_on_the_page(self):
        self.page.goto(ORIGIN)
        link = self.page.locator('[data-lightbox]').first
        link.click()
        self.assertTrue(self.page.locator('dialog').evaluate('(el)=>el.open'))
        self.assertEqual(self.page.url.rstrip('/'), ORIGIN.rstrip('/'))
        self.page.get_by_role('button', name='Close photograph', exact=True).click()
        self.assertTrue(link.evaluate('(el)=>el===document.activeElement'))

    def test_14_text_enlargement_and_short_mobile_menu(self):
        self.page.set_viewport_size({'width': 768, 'height': 900})
        for route in ROUTES:
            self.page.goto(ORIGIN + route)
            # Simulate a user stylesheet: production CSP stays unchanged.
            self.page.evaluate("document.documentElement.style.fontSize='200%'")
            self.assertFalse(self.page.evaluate('document.documentElement.scrollWidth > innerWidth + 1'), route)
        self.page.set_viewport_size({'width': 568, 'height': 320})
        self.page.goto(ORIGIN)
        self.page.locator('.mobile-menu summary').click()
        self.page.locator('.mobile-menu nav a').last.click()
        self.page.wait_for_url('**/archive/')
        self.assertTrue(self.page.locator('h1').is_visible())


if __name__ == '__main__':
    unittest.main(verbosity=2)
